name = "dronery"
defaultTargets = ["Dronery"]
reservoir = false

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[lean_lib]]
name = "Dronery"

[[require]]
name = "mathlib"
scope = "leanprover-community"
